import test from 'node:test';import assert from 'node:assert/strict';
import {CaptureSession,BrowserTranscriber} from '../public/capture.mjs';
import {resolveSpeech} from '../public/speech-pipeline.mjs';
function pcm(rms=.001){return {pcm:new Float32Array(1600).fill(rms),rms,rate:16000};}
function srEvent(text,final=false){const r=[{transcript:text,confidence:.8}];r.isFinal=final;return {resultIndex:0,results:[r]};}
function mockBrowser(){let time=0,seq=0,timers=new Map(),instances=[];const opts={now:()=>time,schedule:(f,ms)=>{const id=++seq;timers.set(id,{f,at:time+ms});return id;},unschedule:id=>timers.delete(id),factory:()=>{const rec={start(){this.onstart?.();},abort(){this.aborted=true;}};instances.push(rec);return rec;}};return {opts,instances,tick(t){time=t;for(const [id,x]of [...timers])if(x.at<=t){timers.delete(id);x.f();}},timers};}
test('recognized quiet speech submits without ever crossing the volume threshold',()=>{const output=[],c=new CaptureSession({onSegment:s=>output.push(s)});c.push(pcm(),0);c.updateText('What is your energy budget?',{final:true},100);c.tick(1100);assert.equal(output.length,1);assert.equal(output[0].text,'What is your energy budget?');});
test('background volume cannot hold a stable final transcript forever',()=>{const output=[],c=new CaptureSession({onSegment:s=>output.push(s)});for(let t=0;t<4000;t+=100){c.push(pcm(t%300===0?.1:.002),t);if(t===1000)c.updateText('How do you estimate the daily use?',{final:true},t);c.tick(t);}assert.equal(output[0].text,'How do you estimate the daily use?');});
test('stalled interim transcript has a bounded submission wait',()=>{const output=[],c=new CaptureSession({onSegment:s=>output.push(s)});c.updateText('What about the data size?',{final:false},0);c.tick(2200);assert.equal(output.length,1);});
test('three consecutive utterances each produce one independent segment',()=>{const output=[],c=new CaptureSession({onSegment:s=>output.push(s)});for(let n=0;n<3;n++){const base=n*4000;for(let t=base;t<base+500;t+=100)c.push(pcm(.001),t);for(let t=base+500;t<base+1500;t+=100)c.push(pcm(.03+(t%300)/10000),t);c.updateText(['What is the energy goal?','And metering?','What is the data size?'][n],{final:true},base+1500);for(let t=base+1500;t<base+3000;t+=100){c.push(pcm(.001),t);c.tick(t);}}assert.equal(output.length,3);assert.deepEqual(output.map(s=>s.text),['What is the energy goal?','And metering?','What is the data size?']);assert.ok(output.every(s=>s.frames.length>0));});
test('manual submit mid-interim restarts the recognizer; next result index zero is visible',()=>{const m=mockBrowser(),texts=[];const b=new BrowserTranscriber({...m.opts,onText:t=>texts.push(t)});b.start();const old=m.instances[0],late=old.onresult;old.onresult(srEvent('How do you define the target'));b.commit();m.tick(150);assert.equal(old.aborted,true);m.instances[1].onresult(srEvent('How do you estimate daily use?',true));late(srEvent('late old question',true));assert.deepEqual(texts,['How do you define the target','How do you estimate daily use?']);b.stop();});
test('error without onend recovers instead of displaying a dead listening state',()=>{const m=mockBrowser(),texts=[];const b=new BrowserTranscriber({...m.opts,onText:t=>texts.push(t)});b.start();m.instances[0].onerror({error:'network'});m.tick(1000);m.tick(1200);assert.equal(m.instances.length,2);m.instances[1].onresult(srEvent('Why normalize the readings?',true));assert.deepEqual(texts,['Why normalize the readings?']);b.stop();assert.equal(m.timers.size,0);});
test('recognizer start exception is retried',()=>{const m=mockBrowser();const factory=m.opts.factory;let first=true;const b=new BrowserTranscriber({...m.opts,factory:()=>{const r=factory();if(first){first=false;r.start=()=>{throw Error('busy');};}return r;}});b.start();m.tick(600);assert.equal(m.instances.length,2);b.stop();});
test('normal engine end preserves unfinished question across reconnection',()=>{const m=mockBrowser(),texts=[];const b=new BrowserTranscriber({...m.opts,onText:t=>texts.push(t)});b.start();m.instances[0].onresult(srEvent('How do you'));m.instances[0].onend();m.tick(150);m.instances[1].onresult(srEvent('define the target?',true));assert.equal(texts.at(-1),'How do you define the target?');b.stop();});
test('watchdog restarts a recognizer that never sends onstart',()=>{const m=mockBrowser(),f=m.opts.factory;const b=new BrowserTranscriber({...m.opts,factory:()=>{const r=f();r.start=()=>{};return r;}});b.start();m.tick(9000);b.watchdog(null);m.tick(9200);assert.equal(m.instances.length,2);b.stop();});
test('manual submission is authoritative and bypasses ASR disagreement',async()=>{const r=await resolveSpeech({manual:true,text:'And metering?',frames:[pcm().pcm],rate:16000},{transcribe:()=>{throw Error('should not run');}});assert.equal(r.question,'And metering?');assert.equal(r.meta.manual,true);assert.deepEqual(r.meta.alternatives,[]);});
test('local ASR outage falls back to usable browser text without a canned clarification',async()=>{const r=await resolveSpeech({text:'How do you calculate the energy use?',frames:[pcm().pcm],rate:16000},{transcribe:async()=>{throw Error('offline');}});assert.equal(r.question,'How do you calculate the energy use?');assert.equal(r.meta.clarify,undefined);});
test('short follow-up and statement-form question are submitted by default',async()=>{for(const text of ['And metering?','I want to know the data size']){const r=await resolveSpeech({text,frames:[],rate:16000},{mode:'fast'});assert.equal(r.filtered,false);assert.equal(r.question,text);}});
test('ASR terminology disagreement retains both texts and still invokes answer path',async()=>{const r=await resolveSpeech({text:'How do you define the energy budget?',frames:[pcm().pcm],rate:16000},{transcribe:async()=>({text:'How do you define the energy reading?',confidence:.5})});assert.equal(r.meta.alternatives.length,2);assert.equal(r.meta.needsReview,true);assert.equal(r.meta.clarify,undefined);});
test('browser timer functions are never called with the recognizer object as receiver',async()=>{
 const fs=await import('node:fs'),vm=await import('node:vm');let calls=0;
 const nativeTimer=function(){assert.notEqual(this?.constructor?.name,'BrowserTranscriber');calls++;return 1;};
 const sandbox={performance:{now:()=>0},setTimeout:nativeTimer,clearTimeout:nativeTimer,Float32Array,Math};
 vm.runInNewContext(fs.readFileSync(new URL('../public/capture.mjs',import.meta.url),'utf8').replace(/^export /gm,'')+'\nglobalThis.Transcriber=BrowserTranscriber;',sandbox);
 const b=new sandbox.Transcriber({factory:()=>({start(){},abort(){}})});b.start();b.commit();b.stop();assert.ok(calls>=3);
});
test('preambles, isolated fragments and repeated ASR noise do not create answer jobs',async()=>{
 for(const text of ['Hello. '.repeat(12),'I have a question','Okay, here is the question.','will you','about','through','deuteronago','. '.repeat(20),'What? '.repeat(15)]){
  const r=await resolveSpeech({text,frames:[],rate:16000},{mode:'fast'});assert.equal(r.defer,true,text);
 }
});
test('repetitive local hallucination cannot displace a coherent browser question',async()=>{const r=await resolveSpeech({text:'How do you estimate the energy use?',frames:[pcm().pcm],rate:16000},{transcribe:async()=>({text:'at the top of the top '.repeat(30)})});assert.equal(r.question,'How do you estimate the energy use?');assert.equal(r.meta.alternatives.length,1);});
test('a substantive short follow-up is answered rather than treated as noise',async()=>{for(const text of ['And metering?','Why not?','Data size?']){const r=await resolveSpeech({text,frames:[],rate:16000},{mode:'fast'});assert.equal(r.question,text);assert.equal(r.defer,undefined);}});
