import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,mkdir,rm,stat} from 'node:fs/promises';
import {Readable} from 'node:stream';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {ComponentManager,sha256} from '../components/manager.mjs';
import {pack,unpack,safeRelative} from '../components/archive.mjs';
import {platform,loadCatalog,languageAllowed} from '../components/catalog.mjs';
const wait=async m=>{for(let n=0;m.busy&&n<200;n++)await new Promise(r=>setTimeout(r,5));assert.equal(m.busy,false);};
async function fixture(t){const dir=await mkdtemp(path.join(tmpdir(),'replymate-components-'));t.after(()=>rm(dir,{recursive:true,force:true}));const source=path.join(dir,'source');await mkdir(source);await writeFile(path.join(source,'index.mjs'),'export const value=42;');const archive=path.join(dir,'fixture.tar.gz'),size=await pack(source,archive);const payload=await readFile(archive);const entry={id:'docs-office',name:'Office',version:'1.0.0',minApp:'2.5.0',platform,protocol:1,format:'tar.gz',entry:'index.mjs',kind:'runtime',dependencies:[],bytes:payload.length,unpackedBytes:size.bytes,sha256:await sha256(archive),url:'https://example.invalid/immutable.tar.gz'};return {dir,entry,payload,archive};}
test('install is verified and transactional; wrong hash and self-test failures retain old version',async t=>{const f=await fixture(t);let fail=false;const m=await new ComponentManager(path.join(f.dir,'data'),[f.entry],{selfTest:async()=>{if(fail)throw Error('self-test failed');}}).init();await m.importFile(f.entry.id,Readable.from([f.payload]));const old=m.entryPath(f.entry.id);assert.match(await readFile(old,'utf8'),/42/);await assert.rejects(m.importFile(f.entry.id,Readable.from([Buffer.from('corrupt')])),/不匹配/);assert.equal(m.entryPath(f.entry.id),old);fail=true;await assert.rejects(m.importFile(f.entry.id,Readable.from([f.payload])),/self-test/);assert.equal(m.entryPath(f.entry.id),old);assert.match(await readFile(old,'utf8'),/42/);});
test('resume resets a partial file when server ignores Range; complete response is never appended',async t=>{const f=await fixture(t);let requested;const m=await new ComponentManager(path.join(f.dir,'data'),[f.entry],{fetcher:async(url,opts)=>{requested=opts.headers.Range;return new Response(f.payload,{headers:{etag:'v1'}});}}).init();await writeFile(m.partial(f.entry),f.payload.subarray(0,20));await writeFile(m.partial(f.entry)+'.json',JSON.stringify({url:f.entry.url,sha256:f.entry.sha256,etag:'v1'}));await m.start(f.entry.id);await wait(m);assert.equal(requested,'bytes=20-');assert.equal([...m.tasks.values()][0].state,'done');assert.match(await readFile(m.entryPath(f.entry.id),'utf8'),/42/);});
test('wrong Content-Range and changed ETag cannot activate an incomplete component',async t=>{const f=await fixture(t);const m=await new ComponentManager(path.join(f.dir,'data'),[f.entry],{fetcher:async()=>new Response(f.payload,{status:206,headers:{etag:'new','content-range':`bytes 0-${f.payload.length-1}/${f.payload.length}`}})}).init();await writeFile(m.partial(f.entry),f.payload.subarray(0,20));await writeFile(m.partial(f.entry)+'.json',JSON.stringify({url:f.entry.url,sha256:f.entry.sha256,etag:'old'}));await m.start(f.entry.id);await wait(m);assert.equal([...m.tasks.values()][0].state,'error');assert.equal(m.state.installed[f.entry.id],undefined);});
test('component manager rejects foreign architectures, protocols, unknown IDs and concurrent writers',async t=>{const f=await fixture(t);const m=await new ComponentManager(path.join(f.dir,'data'),[f.entry]).init();assert.throws(()=>m.entry('https://evil.test'),/未知/);assert.throws(()=>m.compatible({...f.entry,platform:'wrong'}),/架构/);assert.throws(()=>m.compatible({...f.entry,protocol:2}),/更新/);const release=await m.lock();const second=await new ComponentManager(m.dir,[f.entry]).init();await assert.rejects(second.lock(),/另一实例/);await release();});
test('archive extraction rejects traversal, links, duplicates and expansion overflow',async t=>{const f=await fixture(t);for(const name of ['../x','/x','x\\y','x/../y','C:/x','a//b','CON.txt','x/abc.'])assert.throws(()=>safeRelative(name));await assert.rejects(unpack(f.archive,path.join(f.dir,'small'),1),/上限/);const {gunzipSync,gzipSync}=await import('node:zlib');for(const type of ['1','2']){const tar=gunzipSync(f.payload);tar.write(type,156);tar.fill(32,148,156);const sum=[...tar.subarray(0,512)].reduce((a,b)=>a+b,0);tar.write(sum.toString(8).padStart(6,'0')+'\0 ',148);const bad=path.join(f.dir,'bad'+type+'.tgz');await writeFile(bad,gzipSync(tar));await assert.rejects(unpack(bad,path.join(f.dir,'bad'+type),1000),/链接/);}});
test('repair, rollback, uninstall and cache cleanup preserve account and reference data',async t=>{const f=await fixture(t);const m=await new ComponentManager(path.join(f.dir,'data'),[f.entry]).init();await mkdir(path.join(m.dir,'account'));await writeFile(path.join(m.dir,'account/keep'),'account');await m.importFile(f.entry.id,Readable.from([f.payload]));const first=m.entryPath(f.entry.id);await m.importFile(f.entry.id,Readable.from([f.payload]));assert.notEqual(m.entryPath(f.entry.id),first);await m.rollback(f.entry.id);assert.equal(m.entryPath(f.entry.id),first);await m.verify(f.entry.id);await m.uninstall(f.entry.id);assert.equal(m.state.installed[f.entry.id],undefined);assert.equal(await readFile(path.join(m.dir,'account/keep'),'utf8'),'account');await writeFile(m.partial(f.entry),'half');assert.ok((await m.clearCache()).bytes>0);});
test('model catalog has seven immutable hashes and shared language weights',async()=>{const catalog=await loadCatalog(),models=catalog.filter(e=>e.kind==='model');assert.equal(models.length,7);assert.equal(models[0].bytes,574041195);for(const m of models){assert.match(m.sha256,/^[a-f0-9]{64}$/);assert.equal(new URL(m.url).protocol,'https:');}assert.equal(languageAllowed(models[0],'yue'),true);assert.equal(languageAllowed(models[1],'yue'),false);const english=models.find(e=>e.englishOnly);assert.equal(languageAllowed(english,'auto'),false);assert.equal(languageAllowed(english,'zh'),false);assert.equal(languageAllowed(english,'en'),true);});

test('pause survives manager restart, resume succeeds, and cancellation removes partial files',async t=>{const f=await fixture(t);let started;const began=new Promise(r=>started=r);const m=await new ComponentManager(path.join(f.dir,'data'),[f.entry],{fetcher:async(url,{signal})=>new Response(new ReadableStream({start(controller){controller.enqueue(f.payload.subarray(0,20));signal.addEventListener('abort',()=>controller.error(signal.reason),{once:true});started();}}),{headers:{etag:'v1'}})}).init();const task=await m.start(f.entry.id);await began;await m.control(task.id,'pause');await wait(m);assert.equal(task.state,'paused');const recovered=await new ComponentManager(m.dir,[f.entry],{fetcher:async()=>new Response(f.payload,{headers:{etag:'v1'}})}).init();assert.equal(recovered.tasks.get(task.id).state,'paused');await recovered.resume(task.id);await wait(recovered);assert.equal(recovered.tasks.get(task.id).state,'done');await writeFile(m.partial(f.entry),'partial');const cancelled={id:'cancel',items:[f.entry.id],state:'paused'};recovered.tasks.set('cancel',cancelled);await recovered.control('cancel','cancel');await assert.rejects(stat(m.partial(f.entry)),{code:'ENOENT'});});
test('failed activation rolls back the saved registry and restores the old runtime',async t=>{const f=await fixture(t);let fail=false,restores=0;const m=await new ComponentManager(path.join(f.dir,'data'),[f.entry],{afterSwitch:async()=>{restores++;if(fail){fail=false;throw Error('activation failed');}}}).init();await m.importFile(f.entry.id,Readable.from([f.payload]));const old=m.entryPath(f.entry.id);fail=true;await assert.rejects(m.importFile(f.entry.id,Readable.from([f.payload])),/activation failed/);assert.equal(m.entryPath(f.entry.id),old);const reopened=await new ComponentManager(m.dir,[f.entry]).init();assert.equal(reopened.entryPath(f.entry.id),old);assert.equal(restores,3);});
test('disk budget failure never fetches or changes active component state',async t=>{const f=await fixture(t);let requests=0;const m=await new ComponentManager(path.join(f.dir,'data'),[f.entry],{fetcher:async()=>{requests++;return new Response(f.payload);}}).init();m.space=async()=>{throw Error('磁盘空间不足');};const task=await m.start(f.entry.id);await wait(m);assert.equal(task.state,'error');assert.equal(requests,0);assert.equal(m.state.installed[f.entry.id],undefined);});
