import test from 'node:test';import assert from 'node:assert/strict';
import {QuestionStore,TranscriptBuffer,transcriptDecision,looksQuestion} from '../public/logic.mjs';
import {validateWav} from '../asr.mjs';
test('second question queues without cancelling or changing first streaming answer',()=>{const s=new QuestionStore(),q1=s.add('first'),j1=s.next(),q2=s.add('second');assert.equal(s.selected,q1.id);assert.equal(s.next(),null);s.update(q1.id,j1.a.id,{text:'still first'});assert.equal(q2.attempts[0].text,'');s.finish(q1.id,j1.a.id);assert.equal(s.next().q.id,q2.id);assert.equal(q1.attempts[0].text,'still first');});
test('reading hold and pinned navigation survive incoming and completed questions',()=>{const s=new QuestionStore(),q1=s.add('1'),q2=s.add('2');const j=s.next();s.finish(j.q.id,j.a.id);s.tick(100,6000);s.tick(6000,6000);assert.equal(s.selected,q1.id);s.tick(6101,6000);assert.equal(s.selected,q2.id);s.move(-1);s.add('3');s.tick(99999,0);assert.equal(s.selected,q1.id);assert.equal(s.follow,false);});
test('regeneration preserves old answer and late deltas stay with their own attempt',()=>{const s=new QuestionStore(),q=s.add('original'),j=s.next();s.finish(q.id,j.a.id,{text:'old'});const retry=s.enqueue(q.id,'corrected',{corrected:true});s.update(q.id,j.a.id,{text:'old final'});assert.equal(retry.text,'');assert.equal(retry.question,'corrected');assert.equal(q.attempts.length,2);});
function event(text,final,index=0){const r=[{transcript:text,confidence:.9}];r.isFinal=final;const results=Array(index).fill(null);results[index]=r;return {resultIndex:index,results};}
test('partial transcripts do not submit as final and final results are consumed once',()=>{const b=new TranscriptBuffer();b.update(event('how do',false));assert.equal(b.final,'');b.update(event('How do you define power?',true));assert.equal(b.take().text,'How do you define power?');assert.equal(b.take().text,'');b.update(event('What about metering?',true,1));assert.equal(b.take().text,'What about metering?');});
test('sealed interim cannot leak a late final into the next question',()=>{const b=new TranscriptBuffer();b.update(event('first',false));b.clear();b.update(event('first final',true));assert.equal(b.final,'');b.update(event('second',true,1));assert.equal(b.final,'second');});
test('recognizer restart preserves only unconsumed final text',()=>{const b=new TranscriptBuffer();b.update(event('question one',true));b.take();b.update(event('question two',true,1));b.restart();assert.equal(b.take().text,'question two');assert.equal(b.take().text,'');});
test('broken transcript is flagged for the model without a canned answer',()=>{const d=transcriptDecision('unclear','');assert.equal(d.needsReview,true);assert.equal(d.clarify,false);assert.equal(d.answer,undefined);});
test('ASR differences remain visible but do not suppress the model',()=>{assert.equal(transcriptDecision('How do you estimate energy?','How do you estimate power?',{verified:true}).needsReview,true);assert.equal(transcriptDecision('How do you use kWh?','How do you use k W h?',{verified:true}).clarify,false);assert.equal(transcriptDecision('How do you use kWh?','',{confidence:.4}).clarify,false);});
test('question detection handles introductory fillers',()=>{assert.equal(looksQuestion('Okay, so how do you define the energy use?'),true);assert.equal(looksQuestion('We use manual meter readings.'),false);});
test('malformed audio and huge input are rejected before decoder',()=>{assert.throws(()=>validateWav(Buffer.alloc(44)));assert.throws(()=>validateWav(Buffer.alloc(3000000)));});
test('technical-word and negation differences are retained for review',()=>{assert.equal(transcriptDecision('How do you define the energy budget?','How do you define the energy reading?',{verified:true}).needsReview,true);assert.equal(transcriptDecision('Why is this biased?','Why is this not biased?',{verified:true}).needsReview,true);});
test('poor local confidence becomes a review hint',()=>{assert.equal(transcriptDecision('How do you use metering?','How do you use metering?',{verified:true,localConfidence:.3}).needsReview,true);});
test('return to live jumps out of old history to the latest question',()=>{const s=new QuestionStore(),a=s.add('old'),b=s.add('new');s.select(a.id);s.live();assert.equal(s.selected,b.id);assert.equal(s.follow,true);});

test('low browser confidence is retained for review in generic domains',()=>{assert.equal(transcriptDecision('How much energy is used?','',{confidence:.4}).needsReview,true);});
